insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Melonie', 'Bilham', 'Female', '784 Reindahl Hill', 'mbilham0@ihg.com', 850, '1985-10-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Shannen', 'Saurat', 'Female', '84326 Clove Terrace', 'ssaurat1@infoseek.co.jp', 2140, '1993-08-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Carly', 'Sorey', 'Male', '1 Graedel Plaza', 'csorey2@google.com.hk', 1070, '1990-09-05');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ivonne', 'Frears', 'Male', '1 Buell Court', 'ifrears3@livejournal.com', 500, '1996-05-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Tish', 'Turpey', 'Male', '714 Carberry Hill', 'tturpey4@answers.com', 1380, '1985-10-31');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ezmeralda', 'Ennew', 'Female', '45 Kim Hill', 'eennew5@sohu.com', 670, '1996-05-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Germayne', 'Yelding', 'Male', '699 Forest Dale Junction', 'gyelding6@ask.com', 1930, '1990-10-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Jan', 'Grayley', 'Male', '345 Reinke Parkway', 'jgrayley7@myspace.com', 1670, '1995-12-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Karel', 'Kenshole', 'Male', '94 Vermont Alley', 'kkenshole8@java.com', 1960, '1991-10-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Archambault', 'Freschini', 'Female', '2530 Arrowood Plaza', 'afreschini9@tmall.com', 1910, '1996-04-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Lorin', 'Senner', 'Male', '63 Union Drive', 'lsennera@globo.com', 1120, '1993-05-31');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Julee', 'Mateev', 'Male', '4 Sage Street', 'jmateevb@china.com.cn', 650, '1995-02-24');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Arty', 'Pawlata', 'Male', '7351 Dakota Way', 'apawlatac@altervista.org', 570, '1985-02-14');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Nicolea', 'Girardin', 'Female', '72 Commercial Road', 'ngirardind@theguardian.com', 1560, '1996-09-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Loni', 'Wahncke', 'Female', '60327 Meadow Valley Court', 'lwahnckee@blogs.com', 1960, '1995-06-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Erinna', 'Tompkiss', 'Male', '0 Jenifer Hill', 'etompkissf@va.gov', 1640, '1988-05-06');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Bail', 'Bobasch', 'Male', '4 Redwing Court', 'bbobaschg@upenn.edu', 1400, '1992-04-12');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Walker', 'Clarson', 'Male', '1960 Alpine Lane', 'wclarsonh@china.com.cn', 2370, '1991-10-30');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Moria', 'Cardenas', 'Female', '6 Northport Point', 'mcardenasi@bandcamp.com', 2340, '1988-01-21');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Zarla', 'Liston', 'Female', '860 Browning Lane', 'zlistonj@altervista.org', 1320, '1993-11-15');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Lorettalorna', 'Marzelli', 'Male', '0579 Trailsway Crossing', 'lmarzellik@cbc.ca', 2490, '1989-05-09');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Katleen', 'Greger', 'Female', '42 Spenser Lane', 'kgregerl@live.com', 1140, '1999-05-31');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Becky', 'Duddell', 'Female', '162 Northport Point', 'bduddellm@amazon.com', 1360, '1990-07-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Zenia', 'Tutton', 'Female', '68 Golf Course Terrace', 'ztuttonn@scribd.com', 2380, '1998-12-16');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Tessi', 'Richen', 'Female', '6 Drewry Crossing', 'tricheno@mtv.com', 1600, '1985-11-12');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Clarette', 'Knighton', 'Male', '6 Anderson Street', 'cknightonp@cmu.edu', 780, '1997-06-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Cristionna', 'Gudger', 'Male', '270 Westridge Street', 'cgudgerq@timesonline.co.uk', 1210, '1993-11-13');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Bastian', 'Rennock', 'Male', '23 Center Avenue', 'brennockr@senate.gov', 1440, '1998-08-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Oswald', 'Kensington', 'Female', '72217 Nancy Place', 'okensingtons@nps.gov', 2000, '1997-10-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Salvatore', 'Milksop', 'Female', '63132 Homewood Point', 'smilksopt@cloudflare.com', 1850, '1991-05-30');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Rabi', 'McJerrow', 'Male', '85 Westerfield Street', 'rmcjerrowu@jalbum.net', 1430, '1993-04-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Romy', 'Erdely', 'Male', '06 Forster Center', 'rerdelyv@wordpress.com', 2190, '1994-12-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Donella', 'Scargle', 'Male', '80678 North Hill', 'dscarglew@craigslist.org', 1150, '1989-08-14');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Archibaldo', 'Sinclair', 'Female', '48735 Milwaukee Parkway', 'asinclairx@auda.org.au', 1830, '1989-03-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Edward', 'Semble', 'Female', '9 Armistice Plaza', 'esembley@google.com.au', 740, '1985-07-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Tedda', 'Voyce', 'Female', '2 High Crossing Point', 'tvoycez@netscape.com', 1100, '1990-12-31');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Patin', 'Hatter', 'Male', '0137 Kenwood Terrace', 'phatter10@yelp.com', 1990, '1996-04-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Nick', 'Praten', 'Female', '26114 Stoughton Pass', 'npraten11@naver.com', 950, '1987-04-02');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Casie', 'Middlebrook', 'Male', '1 Melrose Way', 'cmiddlebrook12@baidu.com', 970, '1994-01-17');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Barris', 'Trubshaw', 'Male', '001 Knutson Plaza', 'btrubshaw13@ft.com', 1700, '1996-03-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Freemon', 'Collard', 'Male', '5 Prairie Rose Plaza', 'fcollard14@wikipedia.org', 2110, '1988-04-13');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Murielle', 'Sutherel', 'Female', '29 Northridge Street', 'msutherel15@trellian.com', 2380, '1999-08-18');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Kaile', 'Daburn', 'Male', '474 Boyd Hill', 'kdaburn16@psu.edu', 920, '1995-09-24');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Logan', 'Edgeler', 'Female', '711 Mallard Drive', 'ledgeler17@dell.com', 2220, '1987-07-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Guido', 'Raeburn', 'Male', '93225 Kinsman Circle', 'graeburn18@slate.com', 1540, '1989-10-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Baldwin', 'Maccaddie', 'Male', '5415 Manley Center', 'bmaccaddie19@opensource.org', 770, '1997-12-14');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Sharla', 'Roseblade', 'Male', '3 Pine View Circle', 'sroseblade1a@i2i.jp', 2120, '1994-12-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Reinhold', 'Glasson', 'Female', '8 Marquette Circle', 'rglasson1b@twitpic.com', 1300, '1985-11-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Bidget', 'Van der Kruijs', 'Female', '0 Meadow Valley Road', 'bvanderkruijs1c@ca.gov', 1260, '1991-03-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Eda', 'Lettice', 'Male', '0166 Barnett Crossing', 'elettice1d@bing.com', 1490, '1988-02-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Jo ann', 'Tewkesberrie', 'Female', '7 Sherman Hill', 'jtewkesberrie1e@army.mil', 890, '1994-09-12');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Veronika', 'Blaydon', 'Male', '97 Pearson Park', 'vblaydon1f@fc2.com', 1120, '1985-06-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Jessa', 'Marzellano', 'Female', '18556 6th Hill', 'jmarzellano1g@omniture.com', 880, '1989-06-11');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Eleonora', 'Muckeen', 'Female', '09 Charing Cross Point', 'emuckeen1h@uiuc.edu', 1710, '1989-01-17');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Bernadene', 'Libbey', 'Male', '32235 Caliangt Trail', 'blibbey1i@nih.gov', 2490, '1999-06-14');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Joshua', 'Laroux', 'Male', '83 Manitowish Center', 'jlaroux1j@examiner.com', 1850, '1994-04-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Hadleigh', 'McFeat', 'Female', '31 Corry Place', 'hmcfeat1k@theatlantic.com', 740, '1987-10-05');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ardelis', 'Aindrais', 'Female', '0 Hallows Trail', 'aaindrais1l@diigo.com', 1580, '1996-11-09');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Janet', 'Kiwitz', 'Female', '7295 Little Fleur Junction', 'jkiwitz1m@e-recht24.de', 940, '1999-01-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Mellie', 'Beales', 'Female', '060 Riverside Way', 'mbeales1n@umich.edu', 1970, '1994-09-24');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Armstrong', 'Goman', 'Female', '03 Lukken Place', 'agoman1o@buzzfeed.com', 1450, '1996-01-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ninette', 'Bockmaster', 'Male', '84494 Tony Street', 'nbockmaster1p@jimdo.com', 1000, '1986-03-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Devinne', 'Yeiles', 'Male', '216 Harbort Pass', 'dyeiles1q@bizjournals.com', 1840, '1996-11-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Corry', 'Greenhill', 'Female', '7 Westerfield Point', 'cgreenhill1r@uiuc.edu', 2420, '1993-09-17');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Terza', 'Rigeby', 'Male', '858 Rockefeller Crossing', 'trigeby1s@feedburner.com', 1190, '1987-12-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Hoebart', 'Carson', 'Female', '4 Lillian Park', 'hcarson1t@dot.gov', 1430, '1987-12-02');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Grace', 'McCabe', 'Female', '607 Melrose Parkway', 'gmccabe1u@webmd.com', 1800, '1998-04-02');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Emlyn', 'Ashleigh', 'Female', '0367 Westport Plaza', 'eashleigh1v@printfriendly.com', 1810, '1985-03-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Liza', 'Normansell', 'Male', '1674 Bashford Terrace', 'lnormansell1w@nifty.com', 1110, '1996-10-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Rosemary', 'Prestney', 'Female', '69 Lindbergh Terrace', 'rprestney1x@nba.com', 2270, '1996-11-20');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Melly', 'Flett', 'Female', '14 Monument Plaza', 'mflett1y@shop-pro.jp', 1770, '1996-05-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Judah', 'Lavielle', 'Female', '38258 Monument Court', 'jlavielle1z@mozilla.org', 1250, '1994-04-16');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Dasi', 'Le Fevre', 'Female', '739 Talmadge Lane', 'dlefevre20@amazon.co.jp', 1040, '1991-09-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Red', 'Oakes', 'Female', '272 Del Mar Alley', 'roakes21@cornell.edu', 1960, '1994-03-15');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ashil', 'Kid', 'Male', '09 Meadow Vale Circle', 'akid22@storify.com', 1110, '1987-01-02');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Berti', 'Cowtherd', 'Female', '4 Vera Junction', 'bcowtherd23@theguardian.com', 580, '1989-11-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Beauregard', 'Cheverell', 'Male', '2315 Tomscot Avenue', 'bcheverell24@unblog.fr', 1550, '1986-03-24');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Mirella', 'Ferens', 'Female', '87278 Birchwood Lane', 'mferens25@harvard.edu', 990, '1994-11-30');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Queenie', 'Huddart', 'Female', '4 Schurz Circle', 'qhuddart26@lycos.com', 2030, '1987-06-30');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ashia', 'Woffenden', 'Female', '0 Carpenter Street', 'awoffenden27@seesaa.net', 1150, '1991-02-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Sisely', 'Gniewosz', 'Male', '0663 Lake View Lane', 'sgniewosz28@posterous.com', 1850, '1989-01-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Andrey', 'Lyes', 'Female', '859 Bellgrove Court', 'alyes29@51.la', 1470, '1990-09-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Des', 'Boustred', 'Male', '9304 Manitowish Point', 'dboustred2a@harvard.edu', 2280, '1992-12-24');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Eadith', 'Crookston', 'Male', '88288 Monica Trail', 'ecrookston2b@disqus.com', 510, '1988-08-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Bartie', 'Alelsandrowicz', 'Male', '3748 Bonner Circle', 'balelsandrowicz2c@fastcompany.com', 970, '1996-02-25');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Slade', 'Sewart', 'Female', '69 3rd Plaza', 'ssewart2d@theatlantic.com', 2380, '1985-11-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Edna', 'Tweedle', 'Male', '49 Mcguire Drive', 'etweedle2e@sbwire.com', 1220, '1993-05-13');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Austen', 'Dodamead', 'Male', '36165 Stuart Hill', 'adodamead2f@google.com.br', 2460, '1991-12-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Blinni', 'Gunney', 'Male', '6 American Road', 'bgunney2g@nasa.gov', 680, '1986-02-17');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Zacharia', 'Accomb', 'Female', '481 Golden Leaf Circle', 'zaccomb2h@google.pl', 1940, '1985-08-13');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Cyrus', 'Cookney', 'Female', '596 Spaight Junction', 'ccookney2i@pen.io', 1060, '1996-01-17');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Gaye', 'Bromby', 'Female', '2811 Hanover Parkway', 'gbromby2j@washington.edu', 2290, '1986-10-16');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Tana', 'Clem', 'Male', '96562 Oak Valley Place', 'tclem2k@ning.com', 550, '1991-07-11');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Consuela', 'Pordall', 'Male', '94424 Dakota Parkway', 'cpordall2l@yahoo.com', 1120, '1988-06-09');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Normie', 'Dunckley', 'Female', '77056 Trailsway Street', 'ndunckley2m@amazonaws.com', 1310, '1988-05-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Judy', 'Hallsworth', 'Female', '9669 Leroy Trail', 'jhallsworth2n@odnoklassniki.ru', 2240, '1990-01-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Jenifer', 'Farny', 'Female', '37304 Hansons Pass', 'jfarny2o@slashdot.org', 1420, '1998-03-26');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Edita', 'Tinmouth', 'Female', '16 Atwood Street', 'etinmouth2p@themeforest.net', 1060, '1990-10-25');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Cati', 'Fyndon', 'Male', '9 Clove Road', 'cfyndon2q@acquirethisname.com', 1830, '1994-03-03');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Allx', 'Epinay', 'Male', '775 Briar Crest Pass', 'aepinay2r@census.gov', 1760, '1990-07-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Jan', 'Tratton', 'Male', '83 Onsgard Alley', 'jtratton2s@epa.gov', 1550, '1995-08-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Barny', 'Brumhead', 'Female', '3 Schiller Way', 'bbrumhead2t@google.de', 2350, '1988-01-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Bria', 'Lande', 'Female', '239 Oak Street', 'blande2u@altervista.org', 2190, '1989-08-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Marlee', 'Ligoe', 'Female', '5 Warner Trail', 'mligoe2v@bbc.co.uk', 500, '1987-06-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Emmet', 'Wasielewski', 'Female', '9333 East Court', 'ewasielewski2w@delicious.com', 1360, '1996-03-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Barnaby', 'Mattersley', 'Male', '74481 Glendale Road', 'bmattersley2x@elegantthemes.com', 1760, '1997-12-17');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Iggie', 'Marchenko', 'Female', '8 Maple Wood Plaza', 'imarchenko2y@parallels.com', 1350, '1990-04-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Inger', 'Fransewich', 'Male', '1703 Sauthoff Place', 'ifransewich2z@yahoo.com', 2090, '1997-03-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Sydney', 'Lazenby', 'Male', '60 Fallview Road', 'slazenby30@i2i.jp', 1960, '1994-04-06');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Kerry', 'Janc', 'Female', '13440 Morning Road', 'kjanc31@storify.com', 1190, '1992-05-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Spencer', 'Nares', 'Female', '93426 Loomis Terrace', 'snares32@hugedomains.com', 920, '1989-12-13');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Maddi', 'Dimbylow', 'Female', '97 Mccormick Lane', 'mdimbylow33@scientificamerican.com', 1840, '1994-06-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Mina', 'Kernermann', 'Female', '86 Coolidge Place', 'mkernermann34@blogspot.com', 1930, '1997-04-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Collen', 'Gut', 'Female', '91503 Del Sol Parkway', 'cgut35@phpbb.com', 1480, '1993-08-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ibrahim', 'Widdowes', 'Female', '95 Kropf Point', 'iwiddowes36@netscape.com', 1000, '1994-04-13');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Randi', 'Tourot', 'Male', '86 Twin Pines Way', 'rtourot37@bluehost.com', 2060, '1989-09-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Dorri', 'Champness', 'Male', '379 Banding Pass', 'dchampness38@typepad.com', 2060, '1993-07-12');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Adora', 'Pitrollo', 'Female', '53851 Bashford Lane', 'apitrollo39@virginia.edu', 2440, '1994-07-25');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Gus', 'Davis', 'Female', '3529 Pine View Road', 'gdavis3a@amazon.com', 1340, '1986-09-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ollie', 'Melmeth', 'Female', '08 Mendota Circle', 'omelmeth3b@nhs.uk', 1520, '1985-02-24');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Dani', 'Digance', 'Female', '02 Monument Trail', 'ddigance3c@ning.com', 2310, '1989-07-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Belva', 'Worssam', 'Male', '610 Red Cloud Place', 'bworssam3d@oaic.gov.au', 1740, '1998-05-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Gordon', 'Conley', 'Male', '97939 Manley Lane', 'gconley3e@nymag.com', 680, '1985-01-14');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Betsy', 'Frankiss', 'Female', '8 Namekagon Center', 'bfrankiss3f@live.com', 1120, '1987-04-09');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Dane', 'Dwelley', 'Female', '39889 Monterey Terrace', 'ddwelley3g@dmoz.org', 1460, '1993-12-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Sherye', 'Dingle', 'Female', '2 Barnett Park', 'sdingle3h@freewebs.com', 2020, '1986-12-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Duane', 'Wildgoose', 'Female', '614 Acker Avenue', 'dwildgoose3i@t.co', 2230, '1992-02-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Glenn', 'Hoble', 'Female', '346 American Ash Circle', 'ghoble3j@nature.com', 2220, '1989-08-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Claude', 'Fanning', 'Female', '15 Wayridge Junction', 'cfanning3k@livejournal.com', 1580, '1994-11-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Woodman', 'Dreier', 'Female', '447 Bluestem Point', 'wdreier3l@independent.co.uk', 1680, '1992-02-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Kalindi', 'Follett', 'Male', '2022 La Follette Point', 'kfollett3m@dedecms.com', 2090, '1986-01-17');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Camilla', 'Zorzin', 'Female', '113 Cardinal Lane', 'czorzin3n@mysql.com', 1060, '1999-12-26');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Uri', 'Woodyear', 'Male', '650 Sunbrook Plaza', 'uwoodyear3o@blogtalkradio.com', 1920, '1986-01-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Lammond', 'Wettern', 'Female', '480 Washington Trail', 'lwettern3p@yellowpages.com', 840, '1992-03-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Cristian', 'Kobierzycki', 'Female', '45433 Southridge Lane', 'ckobierzycki3q@bbb.org', 920, '1995-02-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Bartholomew', 'Steeples', 'Female', '80994 Eagan Place', 'bsteeples3r@about.com', 920, '1988-04-28');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Atalanta', 'Zimek', 'Female', '70 Carioca Point', 'azimek3s@state.tx.us', 570, '1999-08-14');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Worthington', 'Millward', 'Female', '2855 Towne Hill', 'wmillward3t@google.com.hk', 1840, '1996-05-06');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Odele', 'Milnes', 'Male', '7053 Lyons Center', 'omilnes3u@tiny.cc', 780, '1998-12-06');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Odette', 'Ivatt', 'Male', '2 Pine View Avenue', 'oivatt3v@economist.com', 980, '1989-10-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Dave', 'Bartunek', 'Male', '30 Magdeline Drive', 'dbartunek3w@nationalgeographic.com', 1350, '1995-03-09');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Nels', 'Trevear', 'Male', '7690 Northwestern Parkway', 'ntrevear3x@google.fr', 1050, '1995-09-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Valeda', 'Carslaw', 'Female', '4803 Graedel Pass', 'vcarslaw3y@163.com', 2330, '1992-02-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Hamilton', 'Pillington', 'Female', '9 Rutledge Lane', 'hpillington3z@usda.gov', 1900, '1998-12-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Kermy', 'Brodeau', 'Female', '12333 Troy Center', 'kbrodeau40@t-online.de', 2100, '1985-05-20');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Tiebout', 'Wabe', 'Female', '82390 Autumn Leaf Street', 'twabe41@walmart.com', 2050, '1995-10-12');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Addi', 'Hand', 'Female', '0 Elka Street', 'ahand42@webmd.com', 660, '1988-10-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Pavlov', 'Hillborne', 'Female', '67368 Sycamore Hill', 'phillborne43@ezinearticles.com', 1890, '1985-10-14');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Kalina', 'Buckthorp', 'Female', '729 Ridge Oak Alley', 'kbuckthorp44@w3.org', 1130, '1997-03-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Eben', 'Garett', 'Male', '956 Hoard Street', 'egarett45@reference.com', 1350, '1996-01-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Stormi', 'Gantz', 'Male', '153 Cardinal Point', 'sgantz46@wix.com', 1150, '1999-02-13');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Kevon', 'Mattioli', 'Female', '11366 Jackson Street', 'kmattioli47@ycombinator.com', 1910, '1997-07-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Maxy', 'Wandless', 'Female', '2 Sage Pass', 'mwandless48@csmonitor.com', 2320, '1990-07-11');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Leigha', 'Ninnoli', 'Male', '1489 Butternut Alley', 'lninnoli49@multiply.com', 1070, '1987-08-12');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Robbin', 'Regelous', 'Male', '7 Vahlen Place', 'rregelous4a@amazon.co.uk', 1700, '1986-12-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Desi', 'Goulbourn', 'Male', '2 Buell Terrace', 'dgoulbourn4b@oracle.com', 980, '1986-12-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Karita', 'Hennington', 'Male', '60 Upham Circle', 'khennington4c@yellowbook.com', 1800, '1996-02-26');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Davide', 'Lazarus', 'Male', '60212 Hovde Point', 'dlazarus4d@wp.com', 2370, '1985-03-15');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Reinwald', 'Turl', 'Male', '95263 Becker Place', 'rturl4e@omniture.com', 2400, '1996-01-08');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Etta', 'Cowitz', 'Male', '03 Judy Parkway', 'ecowitz4f@amazon.co.jp', 1100, '1993-10-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Karen', 'Virgoe', 'Male', '83 Onsgard Plaza', 'kvirgoe4g@opensource.org', 790, '1987-03-26');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Devonna', 'Dunbobbin', 'Male', '081 Old Shore Park', 'ddunbobbin4h@opera.com', 1010, '1987-05-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Glennis', 'Asling', 'Male', '60 Larry Terrace', 'gasling4i@furl.net', 1510, '1991-11-07');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Damaris', 'Salery', 'Male', '33 Independence Alley', 'dsalery4j@unesco.org', 520, '1988-05-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Korella', 'Malling', 'Male', '0 Corscot Hill', 'kmalling4k@bloomberg.com', 2470, '1992-11-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Darrick', 'Folca', 'Male', '7218 Gerald Parkway', 'dfolca4l@purevolume.com', 2400, '1994-07-02');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Sherwynd', 'Harroway', 'Female', '9 Hayes Place', 'sharroway4m@columbia.edu', 1420, '1990-05-24');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Delmor', 'Allcott', 'Female', '4057 Menomonie Alley', 'dallcott4n@jigsy.com', 1220, '1995-09-24');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Cozmo', 'Lacroutz', 'Male', '21 Nobel Center', 'clacroutz4o@uiuc.edu', 1720, '1991-10-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Renie', 'Duffrie', 'Male', '55 American Court', 'rduffrie4p@jigsy.com', 1000, '1998-07-11');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Alessandra', 'Messer', 'Male', '34818 La Follette Terrace', 'amesser4q@vistaprint.com', 1200, '1996-04-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Hendrick', 'Mundford', 'Male', '55279 Pennsylvania Parkway', 'hmundford4r@miitbeian.gov.cn', 1750, '1991-11-06');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Chrissy', 'Macquire', 'Female', '6 4th Point', 'cmacquire4s@cdc.gov', 1560, '1989-09-16');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Agatha', 'Splain', 'Male', '04 Oak Valley Center', 'asplain4t@mlb.com', 2150, '1994-09-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Lethia', 'Wallentin', 'Male', '9215 Saint Paul Parkway', 'lwallentin4u@washington.edu', 1180, '1992-11-06');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Lishe', 'Deschlein', 'Female', '17 Comanche Lane', 'ldeschlein4v@forbes.com', 1800, '1996-12-10');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Josefa', 'Packwood', 'Male', '7 Hollow Ridge Park', 'jpackwood4w@bbc.co.uk', 1490, '1992-08-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Deborah', 'Presidey', 'Female', '83 Redwing Lane', 'dpresidey4x@tripod.com', 1900, '1990-04-23');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Kerri', 'Levy', 'Female', '2 Monterey Drive', 'klevy4y@1688.com', 1850, '1990-01-01');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Cally', 'Balchin', 'Male', '45538 Elgar Road', 'cbalchin4z@nasa.gov', 860, '1992-09-18');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Edlin', 'Borthram', 'Male', '275 Declaration Court', 'eborthram50@si.edu', 2490, '1986-11-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Laurette', 'Talton', 'Male', '78 Summit Park', 'ltalton51@altervista.org', 1910, '1988-08-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Charla', 'Siss', 'Male', '94966 Amoth Plaza', 'csiss52@rediff.com', 880, '1985-04-21');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Reidar', 'Merriday', 'Female', '04 Dryden Way', 'rmerriday53@facebook.com', 1040, '1993-04-05');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Frankie', 'Conichie', 'Male', '438 Miller Avenue', 'fconichie54@unblog.fr', 740, '1990-09-22');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Brook', 'Sloegrave', 'Female', '01 Logan Way', 'bsloegrave55@geocities.com', 600, '1987-10-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Pedro', 'Danbury', 'Female', '115 Hoffman Parkway', 'pdanbury56@smh.com.au', 580, '1995-07-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Rodney', 'Willoughway', 'Male', '9 Loomis Center', 'rwilloughway57@naver.com', 1700, '1991-01-03');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Lock', 'Perrington', 'Female', '47 Brentwood Point', 'lperrington58@unc.edu', 1410, '1986-07-27');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Aristotle', 'Beevers', 'Female', '22 Maryland Hill', 'abeevers59@typepad.com', 1930, '1986-11-11');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Viki', 'Durden', 'Female', '6 Marquette Park', 'vdurden5a@ocn.ne.jp', 1440, '1998-02-04');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Ranna', 'Gilham', 'Female', '8581 Lighthouse Bay Lane', 'rgilham5b@bizjournals.com', 770, '1991-05-16');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Flo', 'Lugton', 'Male', '25861 Sunbrook Parkway', 'flugton5c@java.com', 1310, '1991-03-14');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Tadio', 'Codi', 'Male', '09014 Comanche Terrace', 'tcodi5d@ezinearticles.com', 1440, '1999-06-29');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Marlyn', 'Marquiss', 'Female', '4601 Farwell Pass', 'mmarquiss5e@t-online.de', 750, '1995-07-15');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Kort', 'Ilchenko', 'Female', '65535 Charing Cross Place', 'kilchenko5f@sun.com', 1250, '1985-06-05');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Darby', 'Francklyn', 'Female', '102 Clarendon Place', 'dfrancklyn5g@webeden.co.uk', 580, '1991-11-08');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Chev', 'Klewi', 'Male', '491 Troy Trail', 'cklewi5h@usa.gov', 990, '1992-04-30');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Dru', 'McSkeagan', 'Male', '3 Dapin Point', 'dmcskeagan5i@ovh.net', 1940, '1994-09-19');
insert into employee (first_name, last_name, gender, address, email, salary, BIRTH_DAY) values ('Thorny', 'Wattinham', 'Male', '8 Service Point', 'twattinham5j@boston.com', 1170, '1995-01-23');
